apiVersion: v1
kind: Service
metadata:
  name: java-helloworld-service
  labels:
    app: java-helloworld 
spec:
  selector:
    app: java-helloworld 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
